version: "2"

linters:
  default: standard # Uses the recommended default set
  enable:
    - misspell
    - staticcheck
    - errcheck
    - govet

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
    paths:
      - third_party$
      - examples$
    rules:
      - path: '_test\.go'
        text: "SA5011"
        linters:
          - staticcheck
formatters:
  enable:
    - gofmt
    - goimports
