apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-zfs-cleanup-controller
  # change if required
  # namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebs-zfs-cleanup-controller
rules:
  - apiGroups: ["zfs.openebs.io"]
    resources: ["zfsvolumes"]
    verbs: ["get", "list", "watch", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebs-zfs-cleanup-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openebs-zfs-cleanup-controller
subjects:
  - kind: ServiceAccount
    name: openebs-zfs-cleanup-controller
    # change if above changed
    namespace: default
